### PR TITLE
Jason's Updates - 7/17 (FRI)

### PR DESCRIPTION
**Pull request by kwangil-jason-yoo**
New Themes Added 
- Death Comparison: Last week & this week
- Death Cumulative

Theme name edited

Theme selector order edited

Play/Pause/Speed control buttons replaced w Icons

Speed Indicators Added 
-Turn EIU blue color on/off based on speed level

### CODE REVIEW

**Comment by geobarry** [comment]
Looking good! But there is a lot of redundancy, it's a bit confusing. 

USER INTERFACE
1. The slower/faster buttons should only change the speed. If the animation is not playing, it shouldn't start playing when the user presses "slower" or "faster".
2. The speed should be indicated as soon as the page loads. Right now the circles are all gray on page load.
3. Do we really need a reset button? It is so easy to pick a speed now, it seems the reset button isn't necessary.
4. Can you try adding tooltips for each button, with just one word (e.g. "play", "slower"...). I think it is really easy to do, I haven't done it before but check this thread: https://stackoverflow.com/questions/2238239/tooltips-for-button

CODE
The code can still be reduced much more by using for loops instead of if statements. But we can discuss this... for now the user interface is most important.

**Comment by kwangil-jason-yoo** [comment]
Feedback Updated
USER INTERFACE

(Solved) The slower/faster buttons should only change the speed. If the animation is not playing, it shouldn't start playing when the user presses "slower" or "faster".
(Solved) The speed should be indicated as soon as the page loads. Right now the circles are all gray on page load.
(Solved) Do we really need a reset button? It is so easy to pick a speed now, it seems the reset button isn't necessary.
(Solved) Can you try adding tooltips for each button, with just one word (e.g. "play", "slower"...). I think it is really easy to do, I haven't done it before but check this thread: https://stackoverflow.com/questions/2238239/tooltips-for-button

CODE
(Working...) The code can still be reduced much more by using for loops instead of if statements. But we can discuss this... for now the user interface is most important.

**Comment by geobarry** [comment]
The first issue is still not solved. Pressing any speed button (including dots) should only affect the speed setting. It should not start "play" if the animation is stopped and it should not stop "play" if the animation is already started. Right now the problems are when the user clicks a button while the animation is stopped:

- If the animation is stopped, clicking on a dot causes the animation to start. (it should change the speed setting but it should not start the animation)
- If the animation is stopped, clicking on the "faster" or "slower" button does nothing (it should change the speed setting, and this should show in the dots; again this should not start the animation, just change the speed setting)

**Comment by geobarry** [comment]
Good now. I'm going to merge. But I think it can still be improved in terms of ease-of-use. Please ask other people to try using it and give you suggestions to make it cleaner and simpler while keeping the same functionality.

**Pull request merged**
